import '../globals.css'

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { I18nProvider } from '~/components/providers/i18nProvider'
import { ThemeProvider } from '~/components/providers/themeProvider'
import { ColorThemeSwitcher } from '~/components/ui/colorThemeSwitcher'
import MyClient from '~/components/ui/e'
import LanguageSwitcher from '~/components/ui/langSwitcher'
import { Locale } from '~/lib/i18n/config'
import { getServerTranslation } from '~/lib/i18n/server'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout(props: {
  children: React.ReactNode
  params: Promise<{ locale: Locale }>
}) {
  const { params, children } = props
  const resolvedParams = await params
  const locale = resolvedParams.locale

  const t = await getServerTranslation(locale)

  return (
    <html lang={locale}>
      <body className={`${nunito.variable} } antialiased`}>
        <ThemeProvider>
          <I18nProvider locale={locale}>
            <main className="min-h-screen">
              <ColorThemeSwitcher />
              <h1>{t('language')}</h1>
              <MyClient />
              <LanguageSwitcher locale={locale} />
              {children}
            </main>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
