import '../globals.css'

import { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { I18nProvider } from '~/components/providers/i18nProvider'
import { LocaleProvider } from '~/components/providers/localeProvider'
import { QueryProvider } from '~/components/providers/queryProvider'
import { ThemeProvider } from '~/components/providers/themeProvider'
import { Header } from '~/components/shared'
import { getDefaultLocale, isLocale } from '~/lib/i18n'
import { Locale } from '~/lib/i18n/config'
import { getServerTranslation } from '~/lib/i18n/server'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  const safeLocale: Locale = isLocale(locale) ? (locale as Locale) : getDefaultLocale()

  const t = await getServerTranslation(safeLocale)
  return (
    <html lang={safeLocale}>
      <body className={`${nunito.variable} } antialiased`}>
        <ThemeProvider>
          <QueryProvider>
            <LocaleProvider initialLocale={safeLocale}>
              <I18nProvider locale={safeLocale}>
                <main className="min-h-screen">
                  <Header isAuthorised={false} locale={safeLocale} translate={t} />
                  {children}
                </main>
              </I18nProvider>
            </LocaleProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
