import './globals.css'

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { ThemeProvider } from '~/components/providers/themeProvider'
import { ColorThemeSwitcher } from '~/components/ui/colorThemeSwitcher'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} } antialiased`}>
        <ThemeProvider>
          <main className="min-h-screen">
            <ColorThemeSwitcher />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
