import './globals.css'

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} } antialiased`}>
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  )
}
